CREATE TABLE IF NOT EXISTS asset_library (
  asset_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  asset_type VARCHAR(20) NOT NULL,
  teacher_id BIGINT NOT NULL,
  course_id BIGINT NULL,
  visibility ENUM('private', 'public') NOT NULL DEFAULT 'private',
  asset_title VARCHAR(200) NOT NULL,
  asset_description TEXT NULL,
  asset_content TEXT NULL,
  file_path VARCHAR(500) NULL,
  file_name VARCHAR(255) NULL,
  file_size BIGINT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_asset_library_teacher FOREIGN KEY (teacher_id) REFERENCES teacher_user(teacher_id),
  CONSTRAINT fk_asset_library_course FOREIGN KEY (course_id) REFERENCES course_intro(course_id),
  INDEX idx_asset_library_teacher_status (teacher_id, status),
  INDEX idx_asset_library_teacher_visibility (teacher_id, visibility, status),
  INDEX idx_asset_library_course_status (course_id, status),
  INDEX idx_asset_library_type_status (asset_type, status),
  INDEX idx_asset_library_visibility_status (visibility, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
