CREATE TABLE IF NOT EXISTS courseware (
  courseware_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  teacher_id BIGINT NOT NULL,
  course_id BIGINT NOT NULL,
  prep_id BIGINT NOT NULL,
  courseware_title VARCHAR(200) NOT NULL,
  courseware_summary TEXT NULL,
  status ENUM('draft', 'published') NOT NULL DEFAULT 'draft',
  content_json LONGTEXT NOT NULL,
  published_time DATETIME NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_courseware_teacher FOREIGN KEY (teacher_id) REFERENCES teacher_user(teacher_id) ON DELETE CASCADE,
  CONSTRAINT fk_courseware_course FOREIGN KEY (course_id) REFERENCES course_intro(course_id) ON DELETE CASCADE,
  CONSTRAINT fk_courseware_prep FOREIGN KEY (prep_id) REFERENCES teaching_prep(prep_id) ON DELETE CASCADE,
  INDEX idx_courseware_teacher_status (teacher_id, status),
  INDEX idx_courseware_course_status (course_id, status),
  INDEX idx_courseware_prep_status (prep_id, status),
  INDEX idx_courseware_update_time (update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
